//go:build linux

package process

// ReexecArg is the internal re-exec entrypoint argument recognized by
// cmd/glider-runtime's main(), matching runtime.md §1's
// "<binary> __glider_init__" invocation. It is deliberately not documented
// as a user-facing subcommand (runtime.md, master plan Phase 1 §6): calling
// it directly, outside of the exact fd/env contract Run sets up, is
// unsupported and is rejected defensively by RunInit (init.go).
const ReexecArg = "__glider_init__"

// Fixed extra-file-descriptor numbers the child (__glider_init__) reads its
// synchronization pipes from. os/exec.Cmd.ExtraFiles places entry i at fd
// 3+i in the child, with 0/1/2 remaining the inherited stdio (runtime.md
// §3). This ordering is an implementation contract between launcher.go
// (which builds ExtraFiles in this order) and init.go (which reads these
// fixed numbers) — not something the child discovers dynamically, since
// there is exactly one supported invocation shape.
const (
	fdReadyWrite = 3 // child -> parent: "mount setup complete"
	fdGoRead     = 4 // parent -> child: "proceed to pivot_root + exec"
	fdErrWrite   = 5 // child -> parent: error message, or CLOEXEC-closed on exec success
)

// envRootFS and envHostname carry the launch configuration that isn't
// naturally expressed as trailing argv (runtime.md's `-- <cmd> [args...]`
// already carries the workload command). Phase 1 has no need to hide these
// values, so plain environment variables are simpler and more debuggable
// than adding a fourth configuration pipe (visible via `ps`/`/proc/<pid>/environ`,
// which is a feature during development, not a leak of anything sensitive).
const (
	envRootFS   = "_GLIDER_ROOTFS"
	envHostname = "_GLIDER_HOSTNAME"
)

// Config describes a single Phase 1 container launch, corresponding
// directly to `glider-runtime run --rootfs <path> -- <cmd> [args...]`
// (runtime.md §6).
type Config struct {
	// RootFS is a pre-existing directory to use as the container's root
	// filesystem. Phase 1 does no image handling or OverlayFS (Phase 5-7)
	// — the caller is responsible for its contents.
	RootFS string

	// Argv is the workload command and arguments, executed as PID 1 inside
	// the container's namespaces (runtime.md §1, §5).
	Argv []string

	// Hostname is set via sethostname(2) inside the container's UTS
	// namespace (runtime.md §2).
	Hostname string

	// StateDir is the root directory under which this container's state
	// file is written (state.Dir(StateDir, ContainerID)). Defaults to
	// /var/lib/glider/containers if empty; overridable for tests.
	StateDir string

	// ContainerID identifies this container's state record. Generated by
	// the caller (NewContainerID) so it is known before Run starts, which
	// lets error messages and the state file agree on an identity from the
	// very first CREATING write.
	ContainerID string
}

const defaultStateDir = "/var/lib/glider/containers"

func (c Config) stateDir() string {
	if c.StateDir != "" {
		return c.StateDir
	}
	return defaultStateDir
}
