//go:build linux

package process

import (
	"time"

	"github.com/santinomarial/glider/internal/runtime/cgroup"
)

// ReexecArg is the internal re-exec entrypoint argument recognized by
// cmd/glider-runtime's main(), matching runtime.md §1's
// "<binary> __glider_init__" invocation. It is deliberately not documented
// as a user-facing subcommand (runtime.md, master plan Phase 1 §6): calling
// it directly, outside of the exact fd/env contract Run sets up, is
// unsupported and is rejected defensively by RunInit (init.go).
const ReexecArg = "__glider_init__"

// ReexecWorkloadArg enters the short-lived workload security trampoline. It
// installs the Phase 8 policy and execs the real workload, preserving
// glider-init as namespace PID 1.
const ReexecWorkloadArg = "__glider_workload__"

const fdWorkloadExecStatus = 3

// Fixed extra-file-descriptor numbers the child (__glider_init__) reads its
// synchronization pipes from. os/exec.Cmd.ExtraFiles places entry i at fd
// 3+i in the child, with 0/1/2 remaining the inherited stdio (runtime.md
// §3). This ordering is an implementation contract between launcher.go
// (which builds ExtraFiles in this order) and init.go (which reads these
// fixed numbers) — not something the child discovers dynamically, since
// there is exactly one supported invocation shape.
const (
	fdReadyWrite  = 3 // child -> parent: "mount setup complete"
	fdGoRead      = 4 // parent -> child: "proceed to pivot_root + fork/exec workload"
	fdResultWrite = 5 // child -> parent: FAIL/RUNNING result message (protocol.go)
)

// envRootFS, envHostname, envStateDir, envContainerID, and envStopGrace
// carry launch configuration that isn't naturally expressed as trailing
// argv (runtime.md's `-- <cmd> [args...]` already carries the workload
// command). Phase 1 had no need to hide these values, so plain environment
// variables remain simpler and more debuggable than a configuration pipe
// (visible via `ps`/`/proc/<pid>/environ`, a feature during development,
// not a leak of anything sensitive).
//
// envStateDir and envContainerID are new in Phase 2: glider-init durably
// writes the container's terminal EXITED transition itself (docs/adr/0006),
// so it needs to know where and under what ID, independent of whether its
// launcher parent is still alive to tell it anything further.
const (
	envRootFS      = "_GLIDER_ROOTFS"
	envHostname    = "_GLIDER_HOSTNAME"
	envStateDir    = "_GLIDER_STATE_DIR"
	envContainerID = "_GLIDER_CONTAINER_ID"
	envStopGrace   = "_GLIDER_STOP_GRACE"
	envImageEnv    = "_GLIDER_IMAGE_ENV"
	envWorkingDir  = "_GLIDER_WORKING_DIR"
)

// defaultStopGrace is how long glider-init waits after forwarding SIGTERM
// to the workload before escalating to SIGKILL (§6 "Graceful shutdown
// protocol"). Phase 1 used a fixed 10s launcher-side value; Phase 2 keeps
// 10s as the production default (no evidence yet that it's wrong for real
// workloads) but makes it configurable so tests aren't forced to actually
// wait 10s to exercise escalation (Config.StopGrace / envStopGrace).
const defaultStopGrace = 10 * time.Second

// outerBackstopBuffer is added on top of the configured StopGrace to get
// the launcher's own outer escalation deadline against glider-init itself
// (see launcher.go's waitOrStop doc comment). It must be strictly greater
// than zero so that, under normal operation, glider-init's own internal
// escalation always has a chance to complete first — the launcher's
// backstop exists only to bound a hung/buggy glider-init, not to race it.
const outerBackstopBuffer = 5 * time.Second

// Config describes a single Phase 2 container launch, corresponding
// directly to `glider-runtime run --rootfs <path> -- <cmd> [args...]`
// (runtime.md §6).
type Config struct {
	// RootFS is a pre-existing directory to use as the container's root
	// filesystem. Phase 1/2 do no image handling or OverlayFS (Phase 5-7)
	// — the caller is responsible for its contents.
	RootFS string

	// Argv is the workload command and arguments, executed as a supervised
	// child of glider-init (PID 2+ inside the container's namespaces;
	// docs/adr/0006-glider-init-pid1-supervisor.md).
	Argv []string

	// Hostname is set via sethostname(2) inside the container's UTS
	// namespace (runtime.md §2).
	Hostname string

	// StateDir is the root directory under which this container's state
	// file is written (state.Dir(StateDir, ContainerID)). Defaults to
	// /var/lib/glider/containers if empty; overridable for tests.
	StateDir string

	// ContainerID identifies this container's state record. Generated by
	// the caller (NewContainerID) so it is known before Run starts, which
	// lets error messages and the state file agree on an identity from the
	// very first CREATING write.
	ContainerID string

	// StopGrace overrides defaultStopGrace when nonzero. Exposed on Config
	// (rather than only as an env var) so Go-level callers (tests) can set
	// it directly without shelling out.
	StopGrace time.Duration

	// Resources are the container's requested cgroup v2 resource limits
	// (Phase 4, docs/design/cgroups.md). The zero value means no limits
	// requested — every controller is still explicitly configured to
	// "max" (unlimited), not merely left unset (cgroup.Resources' doc
	// comment).
	Resources cgroup.Resources

	// Env and WorkingDir come from the OCI image config when the Phase 5-7
	// image manager prepares RootFS. Env entries use KEY=VALUE form.
	Env []string
	WorkingDir string
}

const defaultStateDir = "/var/lib/glider/containers"

func (c Config) stateDir() string {
	if c.StateDir != "" {
		return c.StateDir
	}
	return defaultStateDir
}

func (c Config) stopGrace() time.Duration {
	if c.StopGrace > 0 {
		return c.StopGrace
	}
	return defaultStopGrace
}
